### ISSUE TITLE
MUSES logo on Github

### ISSUE THREAD

**Issue by jmseigneur** [MusesProject/Muses#2]
Dear JJ,

Would it be possible to have the MUSES logo for the MUSES organization avatar on Github rather than the ugly default one ;-) ?

BR,

Jm

**Comment by JJ** [comment]
I'll see if I can do it. I think it needs an email address or somesuch.

2014-05-30 19:49 GMT+02:00 Jean-Marc Seigneur notifications@github.com:

> Dear JJ,
> 
> Would it be possible to have the MUSES logo for the MUSES organization
> avatar on Github rather than the ugly default one ;-) ?
> 
> BR,
> 
> Jm
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MusesProject/Muses/issues/2.

## 

JJ

**Comment by JJ** [comment]
Done. It was only a matter of uploading a logo. Thanks for the suggestion.

**Comment by jmseigneur** [comment]
Great, thanks!
